from flask import Flask, request, jsonify
from flask_cors import CORS
import numpy as np
import os
from PIL import Image
import io

# TensorFlow is optional - if it OOMs on free tier, use mock predictions
TF_AVAILABLE = False
keras_image = None
try:
    import tensorflow as tf
    from tensorflow.keras.preprocessing import image as keras_image
    TF_AVAILABLE = True
    print("✅ TensorFlow loaded successfully")
except Exception as e:
    print(f"⚠️ TensorFlow not available: {e}. Using mock predictions.")

app = Flask(__name__)
CORS(app)

# Load the model
MODEL_PATH = 'buffalo_breed_model.h5'
CLASSES_PATH = 'classes.txt'

model = None

# Default classes — will be overridden by classes.txt if it exists
DEFAULT_CLASSES = [
    'Holstein', 'Jersey', 'Gir', 'Sahiwal', 'Red Sindhi', 'Tharparkar', 'Kankrej',
    'Murrah', 'Mehsana', 'Surti', 'Jaffarabadi', 'Nili-Ravi', 'Bhadawari',
    'Sirohi', 'Beetal', 'Jamunapari'
]

# Load classes from file first (generated by train.py), fall back to defaults
if os.path.exists(CLASSES_PATH):
    with open(CLASSES_PATH, 'r') as f:
        classes = [line.strip() for line in f.readlines() if line.strip()]
    print(f"✅ Loaded {len(classes)} classes from {CLASSES_PATH}: {classes}")
else:
    classes = DEFAULT_CLASSES
    print(f"⚠️ {CLASSES_PATH} not found. Using default {len(classes)} classes.")

if TF_AVAILABLE and os.path.exists(MODEL_PATH):
    try:
        model = tf.keras.models.load_model(MODEL_PATH)
        print(f"✅ Model loaded successfully. Expected output size: {model.output_shape}")
        # Validate class count matches model output
        model_output_size = model.output_shape[-1]
        if model_output_size != len(classes):
            print(f"⚠️ WARNING: Model outputs {model_output_size} classes but classes list has {len(classes)}. Predictions may be wrong!")
    except Exception as e:
        print(f"⚠️ Could not load model: {e}")
else:
    print("⚠️ Model file not found or TF unavailable. Using mock predictions.")

animal_detector = None
print("ℹ️ Animal detector skipped (mock YOLO used instead). Saves RAM on free tier.")

def get_breed_info(breed_name):
    info = {
        # Buffaloes
        'Murrah': {'type': 'Buffalo', 'origin': 'Haryana, India', 'milkProduction': '2,000 - 2,500 kg', 'characteristics': 'Black, curved horns, massive body', 'description': 'The most popular dairy buffalo.'},
        'Nili-Ravi': {'type': 'Buffalo', 'origin': 'Punjab', 'milkProduction': '1,800 - 2,500 kg', 'characteristics': 'White markings on face/legs', 'description': 'Known as the "Black Gold".'},
        'Jaffarabadi': {'type': 'Buffalo', 'origin': 'Gujarat, India', 'milkProduction': '2,000 - 2,700 kg', 'characteristics': 'Drooping horns, heavy forehead', 'description': 'Heaviest buffalo breed.'},
        'Mehsana': {'type': 'Buffalo', 'origin': 'Gujarat, India', 'milkProduction': '1,200 - 1,500 kg', 'characteristics': 'Intermediate Murrah/Surti features', 'description': 'Consistent yield cross-breed.'},
        'Surti': {'type': 'Buffalo', 'origin': 'Gujarat, India', 'milkProduction': '1,300 - 1,500 kg', 'characteristics': 'Sickle horns, medium size', 'description': 'High fat content in milk.'},
        'Bhadawari': {'type': 'Buffalo', 'origin': 'Uttar Pradesh, India', 'milkProduction': '800 - 1,000 kg', 'characteristics': 'Copper colored body, wedge shape', 'description': 'Famous for extremely high butterfat.'},
        
        # Cows
        'Holstein': {'type': 'Cow', 'origin': 'Netherlands', 'milkProduction': '7,000 - 10,000 kg', 'characteristics': 'Black and white spots, large frame', 'description': 'Highest milk producer globally.'},
        'Jersey': {'type': 'Cow', 'origin': 'Jersey Island, UK', 'milkProduction': '4,000 - 5,000 kg', 'characteristics': 'Fawn color, prominent eyes, small', 'description': 'Produces golden, high-fat milk.'},
        'Gir': {'type': 'Cow', 'origin': 'Gujarat, India', 'milkProduction': '2,100 kg', 'characteristics': 'Red with white spots, prominent forehead', 'description': 'Famous Indian dairy breed.'},
        'Sahiwal': {'type': 'Cow', 'origin': 'Punjab', 'milkProduction': '2,200 kg', 'characteristics': 'Reddish brown, tick resistant', 'description': 'Best indigenous dairy cow of India/Pakistan.'},
        'Red Sindhi': {'type': 'Cow', 'origin': 'Sindh', 'milkProduction': '1,800 kg', 'characteristics': 'Deep red color, compact body', 'description': 'Highly heat tolerant.'},
        'Tharparkar': {'type': 'Cow', 'origin': 'Thar Desert', 'milkProduction': '1,700 kg', 'characteristics': 'White/light grey, lyre horns', 'description': 'Dual-purpose, thrives in deserts.'},
        'Kankrej': {'type': 'Cow', 'origin': 'Gujarat, India', 'milkProduction': '1,750 kg', 'characteristics': 'Silver-grey, large crescent horns', 'description': 'One of the heaviest Indian cattle.'},
        
        # Goats
        'Sirohi': {'type': 'Goat', 'origin': 'Rajasthan, India', 'milkProduction': '0.5 - 1 kg/day', 'characteristics': 'Brown with patches, flat leaf ears', 'description': 'Dual purpose, highly adaptable.'},
        'Beetal': {'type': 'Goat', 'origin': 'Punjab', 'milkProduction': '2 - 3 kg/day', 'characteristics': 'Black/red, roman nose, long ears', 'description': 'Excellent dairy goat.'},
        'Jamunapari': {'type': 'Goat', 'origin': 'Uttar Pradesh, India', 'milkProduction': '2 - 2.5 kg/day', 'characteristics': 'White color, highly pendulous ears', 'description': 'The largest goat breed in India.'}
    }
    return info.get(breed_name, {
        'type': 'Unknown Cattle',
        'origin': 'Unknown',
        'milkProduction': 'Unknown',
        'characteristics': 'N/A',
        'description': 'Information not available for this breed/species.'
    })

def generate_fake_gradcam(img_bytes, seed_hash):
    import hashlib
    import random
    from PIL import ImageFilter, Image
    import io
    
    random.seed(seed_hash)
    base_img = Image.open(io.BytesIO(img_bytes)).convert('RGB')
    width, height = base_img.size
    
    heatmap = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    import PIL.ImageDraw as ImageDraw
    draw = ImageDraw.Draw(heatmap)
    
    for _ in range(3):
        x = random.randint(width//4, 3*width//4)
        y = random.randint(height//4, 3*height//4)
        r = random.randint(min(width, height)//6, min(width, height)//3)
        draw.ellipse((x-r, y-r, x+r, y+r), fill=(random.randint(200,255), random.randint(0, 100), 0, 180))
    
    heatmap = heatmap.filter(ImageFilter.GaussianBlur(min(width, height)//8))
    result = Image.alpha_composite(base_img.convert('RGBA'), heatmap).convert('RGB')
    
    buf = io.BytesIO()
    result.save(buf, format='JPEG')
    import base64
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode('utf-8')

def analyze_image_quality(img_bytes):
    import numpy as np
    from PIL import Image, ImageStat
    import io
    
    img = Image.open(io.BytesIO(img_bytes)).convert('L') # Convert to Grayscale
    stat = ImageStat.Stat(img)
    mean_brightness = stat.mean[0]
    
    # Calculate blur (Variance of Laplacian mock)
    img_arr = np.array(img, dtype=float)
    blur_score = np.var(img_arr)
    
    quality = {
        'brightness': float(mean_brightness),
        'blur': float(blur_score),
        'metrics': {
            'animal_detected': True,
            'lighting_sufficient': bool(60 < mean_brightness < 200),
            'background_clutter': bool(blur_score < 1000)
        }
    }
    return quality

@app.route('/predict/<species>', methods=['POST'])
def predict(species):
    try:
        import traceback
        if 'image' not in request.files:
            return jsonify({'error': 'No image provided'}), 400
        
        file = request.files['image']
        img_bytes = file.read()
        
        # Valid classes based on requested species
        cattle_breeds = ['Holstein', 'Jersey', 'Gir', 'Sahiwal', 'Red Sindhi', 'Tharparkar', 'Kankrej']
        buffalo_breeds = ['Murrah', 'Mehsana', 'Surti', 'Jaffarabadi', 'Nili-Ravi', 'Bhadawari']
        
        if species == 'cattle':
            valid_classes = cattle_breeds
        elif species == 'buffalo':
            valid_classes = buffalo_breeds
        else:
            return jsonify({'error': 'Invalid species requested'}), 400

        # Image Quality Check
        quality = analyze_image_quality(img_bytes)

        import hashlib
        img_hash = hashlib.md5(img_bytes).hexdigest()

        # Mock YOLO Crop
        print("Mock YOLO detection passed. Animal cropped.")
        img = Image.open(io.BytesIO(img_bytes)).convert('RGB')
        img = img.resize((224, 224))

        if model and keras_image is not None:
            # Preprocess using keras image utility (correctly imported as keras_image)
            img_array = keras_image.img_to_array(img)
            img_array = np.expand_dims(img_array, axis=0) / 255.0

            predictions = model.predict(img_array)[0]

            # Filter predictions to only the valid species classes
            filtered_preds = []
            for idx, prob in enumerate(predictions):
                if idx < len(classes) and classes[idx] in valid_classes:
                    filtered_preds.append((classes[idx], float(prob)))

            # Sort by probability descending
            filtered_preds.sort(key=lambda x: x[1], reverse=True)

            results = []
            for breed_name, prob in filtered_preds[:3]:
                results.append({
                    'breed': breed_name,
                    'confidence': round(prob, 4)
                })

            # Fallback: if model gave no valid predictions, return lowest-confidence valid class
            if not results:
                print(f"⚠️ No valid predictions for species '{species}'. Falling back.")
                results = [{'breed': valid_classes[0], 'confidence': 0.1}]

            main_breed = results[0]['breed']
            confidence = results[0]['confidence']
            heatmap_b64 = generate_fake_gradcam(img_bytes, img_hash)
        else:
            import random

            # No model available — use deterministic mock based on image hash
            # so the same image always returns the same result
            random.seed(img_hash)

            main_breed = random.choice(valid_classes)
            confidence = round(random.uniform(0.75, 0.98), 2)

            candidates = [b for b in valid_classes if b != main_breed]
            random.shuffle(candidates)

            results = [
                {'breed': str(main_breed), 'confidence': float(confidence)},
                {'breed': str(candidates[0]) if len(candidates) > 0 else str(main_breed), 'confidence': round(random.uniform(0.08, 0.15), 2)},
                {'breed': str(candidates[1]) if len(candidates) > 1 else str(main_breed), 'confidence': round(random.uniform(0.02, 0.07), 2)}
            ]

            random.seed()  # Reset seed
            heatmap_b64 = generate_fake_gradcam(img_bytes, img_hash)

        # Get additional info
        breed_info = get_breed_info(main_breed)
        
        return jsonify({
            'prediction': main_breed,
            'confidence': confidence,
            'top3': results,
            'info': breed_info,
            'heatmap': heatmap_b64,
            'quality': quality['metrics'],
            'mock': model is None  # Tells the client this is a mock prediction, not a real AI result
        })
    except Exception as e:
        trace = traceback.format_exc()
        print("PYTHON CRASH:", trace)
        return jsonify({'error': str(e), 'trace': trace}), 500

if __name__ == '__main__':
    app.run(port=8000, debug=True)
